// creating_wc/using-svelte/src/MyButton.svelte
<svelte:options tag="my-svelte-button"/>

<button>
  <span><slot /></span>
</button>

<style>
  button {
    display: inline-block;
    color: #5c8012;
    font-size: 18px;
    font-weight: 500;
    font-family: "Futura";
    background-color: white;
    border: 1px solid grey;
    border-radius: 4px;
    padding: 8px;
    margin: 8px;
    transition: box-shadow 0.4s ease;
    user-select: none;
  }
  button:hover {
    box-shadow: 0 4px 32px 0 rgba(0, 0, 0, 0.161);
  }
  button:active {
    background-color: grey;
  }
</style>

// creating_wc/my-button.js
const template = document.createElement('template');
template.innerHTML = `
<style>
button {
  color: #5c8012;
  background-color: white;
  border: 1px solid grey;
  display: inline-block;
  padding: 8px;
  margin: 8px;
  border-radius: 4px;
  user-select: none;
  font-size: 18px;
  font-weight: 500;
  font-family: "Futura";
  transition: box-shadow .4s ease;
}
button:hover {
  box-shadow: 0 4px 32px 0 rgba(0,0,0,.161);
}
button:active {
  background-color: grey;
}
</style>
<button>
  <span><slot/></span>
</button>`;

class MyButton extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.appendChild(template.content.cloneNode(true));
  }
}


// 2.
window.customElements.define('my-button', MyButton);
