// svelte/src/MyCounter.svelte
<svelte:options tag="my-svelte-counter" />

<script>
  export let count = 0;
  function inc() {
    count++;
  }
</script>

<button on:click={inc}>
  Clicked {count} times
</button>

<style>
  button {
    color: #5c8012;
    background-color: white;
    border: 1px solid grey;
    border-radius: 4px;
    padding: 8px;
    margin: 8px;
    transition: box-shadow 0.4s ease;
    user-select: none;
    cursor: pointer;
  }
  button:hover {
    box-shadow: 0 4px 32px 0 rgba(0, 0, 0, 0.161);
  }
  button:focus {
    outline: none;
    border-color: black;
  }
</style>

// creating_wc/my-counter.js
const counterTemplate = document.createElement("template");
counterTemplate.innerHTML = `
<style>
button {
  display: inline-block;
  color: #5c8012;
  font-size: 18px;
  font-weight: 500;
  font-family: "Futura";
  background-color: white;
  border: 1px solid grey;
  border-radius: 4px;
  padding: 8px;
  margin: 8px;
  transition: box-shadow .4s ease;
  user-select: none;
}
button:hover {
  box-shadow: 0 4px 32px 0 rgba(0,0,0,.161);
}
button:active {
  background-color: grey;
}
</style>
<button id="inc">
  Clicked <span id="count">0</span> times
</button>`;

class MyCounter extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: "open" });
    this.shadowRoot.appendChild(counterTemplate.content.cloneNode(true));
  }

  connectedCallback() {
    this.shadowRoot.getElementById("inc").addEventListener("click", () => {
      this.count++;
    });

    if (!this.hasAttribute("count")) {
      this.setAttribute("count", 0);
    }
  }

  disconnectedCallback() {
    this.shadowRoot.getElementById("count").removeEventListener("click");
  }

  static get observedAttributes() {
    return ["count"];
  }

  attributeChangedCallback(name, oldCount, newCount) {
    this.shadowRoot.getElementById("count").innerHTML = newCount;
  }

  get count() {
    return this.getAttribute("count");
  }

  set count(newCount) {
    this.setAttribute("count", newCount);
  }
}

window.customElements.define("my-counter", MyCounter);
